name: Full CI/CD Pipeline with Deploy Approval

on:
  push:
    branches:
      - main  # Run only on push to `main`
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: true
        default: 'localhost'
        type: choice
        options:
          - localhost

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t app:latest .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet"  # Replace with `npm test` when ready

  deploy-approval:
    name: Deploy Approval
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: localhost  # Approval required before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Approval step before deployment
        run: echo "Waiting for approval before deployment..." 

  deploy:
    name: Deploy to Localhost
    runs-on: ubuntu-latest
    needs: deploy-approval
    if: github.event_name == 'workflow_dispatch'  # Triggered manually via workflow_dispatch
    environment:
      name: localhost  # Approval required for deployment
      url: http://localhost:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t app:latest .

      - name: Deploy to localhost
        run: |
          echo "Deploying to localhost..."
          # SSH to your local machine (replace with actual IP and username)
          ssh -o StrictHostKeyChecking=no user@your_local_ip "
            docker pull app:latest &&
            docker stop app || true &&
            docker rm app || true &&
            docker run -d -p 3000:3000 --name app app:latest
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          LOCAL_IP: ${{ secrets.LOCAL_IP }}  # Add this secret in GitHub Secrets

