name: Manual CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Only for build/test

  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to run'
        required: true
        default: 'migrate'
        type: choice
        options:
          - migrate
          - deploy-staging
          - deploy-production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "Run your tests here" # Replace with `npm test`

  migrate:
    name: Run DB Migration
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'migrate'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "Run your migration here" # e.g., npx prisma migrate deploy

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy-staging'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "Deploying to staging..." # Add real staging deploy commands

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy-production'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "Deploying to production..." # Add real prod deploy commands
