name: Deployment Pipeline

on:
  push:
    branches:
      - main   # automatic build and test on push
  workflow_dispatch:   # manual trigger for migrate and deploy with environment input
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: production
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet"  # Replace with `npm test`

  migrate:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: ${{ github.event.inputs.environment }}
      url: http://10.185.125.191:3000/
    if: github.event_name == 'workflow_dispatch'   # ONLY runs on manual trigger

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run DB migration
        run: |
          echo "Running DB migration"
          # Uncomment and replace with your actual migration command:
          # npx prisma migrate deploy

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: migrate
    environment:
      name: ${{ github.event.inputs.environment }}
      url: http://10.185.125.191:3000/
    if: github.event_name == 'workflow_dispatch'   # ONLY runs on manual trigger

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and run Docker container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/app:latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 3000:3000 --name app ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Verify deployment
        run: docker ps
