name: Full CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Build & Test on every push

  workflow_dispatch:
    inputs:
      action:
        description: 'Choose manual job to run'
        required: true
        default: 'migrate'
        type: choice
        options:
          - migrate
          - deploy-staging
          - deploy-production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet" # Replace with `npm test`

  migrate:
    name: DB Migrate
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'migrate'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run migration
        run: |
          echo "Running database migration"
          # npx prisma migrate deploy

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy-staging'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging"
          # Add real deploy logic here

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy-production'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to Production
        run: |
          echo "Deploying to production"
          # Add real deploy logic here
