name: CI + CD Dev

on:
  push:
    branches:
      - dev   # Only trigger on dev branch
  workflow_dispatch:   # Optional: manual trigger
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: echo "✅ Build successful"

  DeployDev:
    name: Deploy to Dev
    needs: [Build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t myapp:dev .
      - name: Run Docker container
        run: |
          docker stop myapp-dev || true
          docker rm myapp-dev || true
          docker run -d --name myapp-dev -p 3001:3000 myapp:dev
