name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted   # run on your own machine with Docker installed
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo "✅ Build successful"

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:dev .

      - name: Run Docker container
        run: |
          docker stop myapp-dev || true
          docker rm myapp-dev || true
          docker run -d --name myapp-dev -p 3001:3000 myapp:dev

  DeployStaging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:staging .

      - name: Run Docker container
        run: |
          docker stop myapp-staging || true
          docker rm myapp-staging || true
          docker run -d --name myapp-staging -p 3002:3000 myapp:staging

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker container
        run: |
          docker stop myapp-prod || true
          docker rm myapp-prod || true
          docker run -d --name myapp-prod -p 3000:3000 myapp:latest
